### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by innir** [arnef/bewegungsmelder-android#10]
Hi,

with `'com.android.support:appcompat-v7:25.2.0'` in `build.gradle` Bewegungsmelder crashes on start with:

`java.lang.IllegalStateException: Fragment de.arnefeil.bewegungsmelder.MainActivity.EventsSectionFragment must be a public static class to be  properly recreated from instance state.`

using `'com.android.support:appcompat-v7:23.4.0'` instead fixes the problem - but is probably not the best solution...

**Comment by arnef** [comment]
changed the build tools version and downgrade appcompat to 23.4.0.
You're right not the best solution - but works for me
