### ISSUE TITLE
fdroid repository

### ISSUE THREAD

**Issue by nununu1** [arnef/bewegungsmelder-android#6]
Hallo Arne,

es wäre total toll, wenn der Bewegungsmelder auch bei https://f-droid.org/ verfügbar wäre. Viele Menschen, die sich für den Bewegungsmelder interessieren möchten den Google Store nicht nutzen.

Hier gibt es eine FAQ, wie du den Bewegungsmelder in fdroid, dem Repository für freie Software einstellen kannst: https://f-droid.org/wiki/page/FAQ_-_App_Developers

Danke dir!

**Comment by krt16s** [comment]
Ref: https://github.com/arnef/bewegungsmelder-android/issues/7

**Comment by innir** [comment]
Ist er doch mittlerweile. -> fixed
